#!/bin/sh -e
echo "Bootstrapping qemu-uae..."
git submodule update --init dtc
git submodule update --init pixman
cd pixman
NOCONFIGURE=1 ./autogen.sh
rm -f test-driver
cd ..
echo "Bootstrap done, you can now run ./configure"
