#!/bin/sh -e

CFLAGS="-DQEMU_UAE"

CFLAGS="-DDEBUG_UNASSIGNED $CFLAGS"
CFLAGS="-DDEBUG_OP $CFLAGS"
CFLAGS="-DDEBUG_EXCEPTIONS $CFLAGS"

CFLAGS="-DDEBUG_DISAS $CFLAGS"

CFLAGS="-DDEBUG_MMU $CFLAGS"
# CFLAGS="-DDEBUG_BATS $CFLAGS"
# CFLAGS="-DDUMP_PAGE_TABLES $CFLAGS"
# CFLAGS="-DDEBUG_SOFTWARE_TLB $CFLAGS"
# CFLAGS="-DFLUSH_ALL_TLBS $CFLAGS"

OS_NAME=`uname -s`
case $OS_NAME in
MINGW32*)
	export CC=gcc
	export CXX=g++
;;
*)
	CFLAGS="-fPIC $CFLAGS"
;;
esac

CFLAGS="$CFLAGS" ./configure \
--target-list=ppc-softmmu \
--disable-tools \
--disable-werror \
--disable-strip \
--disable-sdl \
--disable-stack-protector \
--disable-gtk \
--disable-virtfs \
--disable-vnc \
--disable-xen \
--disable-brlapi \
--disable-curses \
--disable-curl \
--disable-bluez \
--disable-slirp \
--disable-kvm \
--disable-rdma \
--disable-user \
--disable-uuid \
--disable-vde \
--disable-netmap \
--disable-cap-ng \
--disable-attr \
--disable-docs \
--disable-vhost-net \
--disable-spice \
--disable-libiscsi \
--disable-libnfs \
--disable-smartcard-nss \
--disable-libusb \
--disable-lzo \
--disable-snappy \
--disable-guest-agent \
--disable-seccomp \
--disable-glusterfs \
--disable-tpm \
--disable-libssh2 \
--disable-vhdx \
--disable-quorum \
--disable-numa \
--disable-coroutine-pool \
--disable-pie \
"$@"
